---
layout: page
---
<div class="container">
  <h1>Contact</h1>
  
  <h2>Impressum</h2>

  Legal notice according to §5 TMG (German Act for Telemedia Services) and §55 RStV (German Interstate Treaty on Broadcasting):

  <address>
    <strong>Dipl.-Math. Sebastian Niemann</strong><br />
    Phone: +49 511 / 762 – 19732 <br />
    E-Mail: <a href="mailto:niemann@sra.uni-hannover.de">niemann@sra.uni-hannover.de</a>
  </address>

  <address>
    <strong>Leibniz Universität Hannover</strong><br />
    Institut für Systems Engineering <br />
    Fachgebiet System- und Rechnerarchitektur <br />
    Appelstraße 4
    D-30167 Hannover
  </address>

  <div class="embed-responsive embed-responsive-16by9 text-center">
    <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10379709.003185757!2d8.419323221016729!3d50.569344244445766!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b073629d48477b%3A0xad9aa9c71024c8af!2sLeibniz+Universit%C3%A4t+Hannover!5e0!3m2!1sen!2sus!4v1420163111597"></iframe>
  </div>

  <h2>Google Analytics</h2>

  <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google's collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under https://tools.google.com/dlpage/gaoptout?hl=en-GB.</p>

  <p>You can refuse the use of Google Analytics by clicking on the following link. An opt-out cookie will be set on the computer, which prevents the future collection of your data when visiting this website: <a href="javascript:gaOptout()">Click here to opt-out of Google Analytics</a></p>

  <p>Further information concerning the terms and conditions of use and data privacy can be found at <a href="http://www.google.com/analytics/terms/gb.html">http://www.google.com/analytics/terms/gb.html</a> or at <a href="https://www.google.de/intl/en_uk/policies/">https://www.google.de/intl/en_uk/policies/</a>. Please note that on this website, Google Analytics code is supplemented by "gat._anonymizeIp();" to ensure an anonymized collection of IP addresses (so called IP-masking).</p>
</div>