#pragma once

/**

*/
  arma::mat haltonSequence(
      const arma::uvec& bases,
      const arma::uvec& seeds,
      const arma::uword numberOfElements) {
    assert(!bases.is_empty() && "haltonSequence: The bases must not be empty.");
    assert(arma::size(bases) == arma::size(seeds) && "haltonSequence: The number of bases must be equal to the number of seeds.");
    assert(arma::all(bases > 1) && "haltonSequence: All bases must be greater than 1.");

    if (numberOfElements == 0) {
      return {};
    }

    // A Halton sequence is generated by producing a Van der Corput sequence for each dimension.
    arma::mat sequence(seeds.n_elem, numberOfElements);
    for (arma::uword n = 0; n < sequence.n_rows; ++n) {
      sequence.row(n) = vanDerCorputSequence(bases(n), seeds(n), numberOfElements).t();
    }

    return sequence;
  }