find_program(OCTAVE_CONFIG NAMES octave-config)
if (OCTAVE_CONFIG)
  execute_process(COMMAND ${OCTAVE_CONFIG} -p OCTFILEDIR OUTPUT_VARIABLE OCTAVE_MEX_FILES_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND ${OCTAVE_CONFIG} -v OUTPUT_VARIABLE OCTAVE_VERSION_STRING OUTPUT_STRIP_TRAILING_WHITESPACE)    

  if (OCTAVE_VERSION_STRING)                 
    string(REGEX REPLACE "([0-9]+).*" "\\1" OCTAVE_MAJOR_VERSION ${OCTAVE_VERSION_STRING})
    string(REGEX REPLACE "[0-9]+\\.([0-9]+).*" "\\1" OCTAVE_MINOR_VERSION ${OCTAVE_VERSION_STRING})
    string(REGEX REPLACE "[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" OCTAVE_PATCH_VERSION ${OCTAVE_VERSION_STRING})               
  endif()  
endif() 

find_program(OCTAVE_MKOCTFILE NAMES mkoctfile)
if (OCTAVE_MKOCTFILE)
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p CPPFLAGS OUTPUT_VARIABLE OCTAVE_CPPFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_CPPFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_CPPFLAGS ${OCTAVE_CPPFLAGS})
    separate_arguments(OCTAVE_CPPFLAGS WINDOWS_COMMAND ${OCTAVE_CPPFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p CXXPICFLAG OUTPUT_VARIABLE OCTAVE_CPICFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_CPICFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_CPICFLAGS ${OCTAVE_CPICFLAGS})
    separate_arguments(OCTAVE_CPICFLAGS WINDOWS_COMMAND ${OCTAVE_CPICFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p INCFLAGS OUTPUT_VARIABLE OCTAVE_INCFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_INCFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_INCFLAGS ${OCTAVE_INCFLAGS})
    string(REGEX REPLACE "-I" "" OCTAVE_INCFLAGS ${OCTAVE_INCFLAGS})
    separate_arguments(OCTAVE_INCFLAGS WINDOWS_COMMAND ${OCTAVE_INCFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p CXXFLAGS OUTPUT_VARIABLE OCTAVE_CXXFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_CXXFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_CXXFLAGS ${OCTAVE_CXXFLAGS})
    separate_arguments(OCTAVE_CXXFLAGS WINDOWS_COMMAND ${OCTAVE_CXXFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p DL_LDFLAGS OUTPUT_VARIABLE OCTAVE_DL_LDFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_DL_LDFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_DL_LDFLAGS ${OCTAVE_DL_LDFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p LFLAGS OUTPUT_VARIABLE OCTAVE_LFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_LFLAGS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_LFLAGS ${OCTAVE_LFLAGS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p OCT_LINK_OPTS OUTPUT_VARIABLE OCTAVE_OCT_LINK_OPTS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_OCT_LINK_OPTS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_OCT_LINK_OPTS ${OCTAVE_OCT_LINK_OPTS})
  endif()
  execute_process(COMMAND ${OCTAVE_MKOCTFILE} -p OCT_LINK_DEPS OUTPUT_VARIABLE OCTAVE_OCT_LINK_DEPS OUTPUT_STRIP_TRAILING_WHITESPACE)
  if (OCTAVE_OCT_LINK_DEPS)
    string(REGEX REPLACE "(\\\\)" "/" OCTAVE_OCT_LINK_DEPS ${OCTAVE_OCT_LINK_DEPS})
  endif()
  
  set(OCTAVE_COMPILE_OPTIONS ${OCTAVE_CPPFLAGS} ${OCTAVE_CPICFLAGS} ${OCTAVE_CXXFLAGS})
  set(OCTAVE_INCLUDE_DIR ${OCTAVE_INCFLAGS})
  set(OCTAVE_LINK_OPTIONS ${OCTAVE_DL_LDFLAGS} ${OCTAVE_OCT_LINK_OPTS})
  set(OCTAVE_LIBRARIES ${OCTAVE_LFLAGS} -loctinterp -loctave ${OCTAVE_OCT_LINK_DEPS})
  set(OCTAVE_SUFFIX ".mex")

  unset(OCTAVE_CPPFLAGS)
  unset(OCTAVE_CPICFLAGS)
  unset(OCTAVE_CXXFLAGS)
  unset(OCTAVE_DL_LDFLAGS)
  unset(OCTAVE_LFLAGS)
  unset(OCTAVE_OCT_LINK_OPTS)
  unset(OCTAVE_OCT_LINK_DEPS)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Octave
  FOUND_VAR OCTAVE_FOUND
  REQUIRED_VARS OCTAVE_CONFIG OCTAVE_MEX_FILES_DIR OCTAVE_MKOCTFILE OCTAVE_COMPILE_OPTIONS OCTAVE_INCLUDE_DIR OCTAVE_LINK_OPTIONS OCTAVE_LIBRARIES OCTAVE_SUFFIX
  VERSION_VAR OCTAVE_VERSION_STRING)

mark_as_advanced (
  OCTAVE_FOUND
  OCTAVE_CONFIG
  OCTAVE_MEX_FILES_DIR
  OCTAVE_VERSION_STRING
  OCTAVE_MAJOR_VERSION
  OCTAVE_MINOR_VERSION
  OCTAVE_PATCH_VERSION
  OCTAVE_MKOCTFILE
  OCTAVE_COMPILE_OPTIONS
  OCTAVE_INCLUDE_DIR
  OCTAVE_LINK_OPTIONS
  OCTAVE_LIBRARIES
  OCTAVE_SUFFIX)